#Enter BungeeCord IP address or IP address that you would like to whitelist
whitelist-ip: 127.0.0.2

#Players will receive this message if their IP address doesn't match bungeeip above
kick-message: "&4Direct access is not allowed! Please join using the Hub server."